---
- name: Install the opendatapolicing source code and watch service on the target. 
  hosts: localhost
  vars: 
    PROJECT_NAME: opendatapolicing
    GITHUB_ORG: "{{ PROJECT_NAME }}"
    PROJECT_REPO: "git@github.com:computate/{{ PROJECT_NAME }}.git"
    PROJECT_SRC: "{{ playbook_dir | dirname }}"
    PROJECT_JAVA_PACKAGE: com.opendatapolicing.enus
  tasks: 
#    - include_role:
#        name: computate.computate_postgres
#    - include_role:
#        name: computate.computate_zookeeper
#    - include_role:
#        name: computate.computate_solr
    - include_role:
        name: computate.computate_project
      vars: 
        PROJECT_SERVICES: 
          - PROJECT_NAME: "{{ PROJECT_NAME }}"
            PROJECT_SRC: "{{ PROJECT_SRC }}"
            PROJECT_JAVA_PACKAGE: "{{ PROJECT_JAVA_PACKAGE }}"

