---
- name: Refresh the southerncoalition page-design data
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_refresh_enUS, DATA_NAME_VAR: page-design, DATA_URI: /api/page-design }
- name: Refresh the southerncoalition html-part data
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_refresh_enUS, DATA_NAME_VAR: html-part, DATA_URI: /api/html-part }
