---
- name: Sign in to the application through the SSO server
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_login_enUS }
- name: Backup the southerncoalition page-design data.
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_backup_enUS, DATA_NAME_VAR: page-design, DATA_URI: /api/admin/page-design, DATA_ROWS: 500 }
- name: Backup the southerncoalition html-part data.
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_backup_enUS, DATA_NAME_VAR: html-part, DATA_URI: /api/html-part, DATA_ROWS: 500 }
- name: Backup the southerncoalition state data.
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_backup_enUS, DATA_NAME_VAR: state, DATA_URI: /api/state, DATA_ROWS: 500 }
- name: Backup the southerncoalition agency data.
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_backup_enUS, DATA_NAME_VAR: agency, DATA_URI: /api/agency, DATA_ROWS: 500 }
- name: Backup the southerncoalition reportcard data.
  hosts: "{{ target }}"
  connection: local
  roles:
    - { role: southerncoalition_backup_enUS, DATA_NAME_VAR: reportcard, DATA_URI: /api/reportcard, DATA_ROWS: 500 }
